### ISSUE TITLE
Practica 1_ Luis gerardo

### ISSUE THREAD

**Issue by LuisGerardo814** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-LuisGerardo814#2]
[Practica 1_LuisGerardoOrtizGonzalez.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-LuisGerardo814/files/6184478/Practica.1_LuisGerardoOrtizGonzalez.pdf)

**Comment by ObedG** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
